apiVersion: 1

deleteDatasources:
  - name: InfluxDB - Raw
    orgId: 1
  - name: InfluxDB - Processed
    orgId: 1

datasources:
  - name: InfluxDB - Raw
    uid: iot-influx-raw
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_RAW_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}

  - name: InfluxDB - Processed
    uid: iot-influx-processed
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: false
    editable: false
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_PROCESSED_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
